# Generated by Django 4.1.1 on 2022-09-21 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('us_nombre', models.TextField(max_length=30, verbose_name='nombres')),
                ('us_apellidos', models.TextField(max_length=30, verbose_name='apellidos')),
                ('us_edad', models.IntegerField(default=0, verbose_name='edad')),
                ('us_direccion', models.TextField(max_length=50, verbose_name='direccion')),
                ('us_telefono', models.IntegerField(default=0, verbose_name='telefono')),
                ('us_email', models.EmailField(max_length=15, verbose_name='email')),
                ('us_password', models.CharField(max_length=10, verbose_name='Password')),
                ('us_num_documento', models.IntegerField(unique=True, verbose_name='documento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('pa_direccion', models.TextField(max_length=30, verbose_name='direccion')),
                ('pa_ciudad', models.TextField(max_length=30, verbose_name='ciudad')),
                ('pa_fechaNacimiento', models.DateField()),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuariopa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('med_especializacion', models.TextField(max_length=30, verbose_name='especializacion')),
                ('med_registro', models.TextField(max_length=30, verbose_name='registro')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuariome', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historia_medica',
            fields=[
                ('id_Historiamed', models.AutoField(primary_key=True, serialize=False)),
                ('hi_oximetria', models.TextField(max_length=30, verbose_name='oximetria')),
                ('hi_glisemia', models.TextField(max_length=30, verbose_name='glisemia')),
                ('hi_presionart', models.TextField(max_length=30, verbose_name='presionart')),
                ('hi_frecuenciares', models.TextField(max_length=30, verbose_name='frecuenciares')),
                ('hi_temperatura', models.TextField(max_length=30, verbose_name='temperatura')),
                ('paciente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='hencasa.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('fa_parentesco', models.TextField(max_length=30, verbose_name='parentesco')),
                ('fa_correo', models.TextField(max_length=30, verbose_name='correo')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuariofa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('dia_sugerencias', models.TextField(max_length=30, verbose_name='sugerencias')),
                ('dia_fecha', models.DateField()),
                ('hismedico_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_medica', to='hencasa.historia_medica')),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id_auxiliar', models.AutoField(primary_key=True, serialize=False)),
                ('au_descripcionasig', models.TextField(max_length=30, verbose_name='descripcionasig')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioau', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('medico_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoasi', to='hencasa.medico')),
                ('paciente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacienteasi', to='hencasa.paciente')),
            ],
        ),
    ]
