from .familiarSerializer import FamiliarSerializer
from .medicoSerializer import MedicoSerializer
from .pacienteSerializer import PacienteSerializer
from .usuarioSerializer import UsuarioSerializer
from .asignacionSerializer import AsignacionSerializer
from .diagnosticoSerializer import DiagnosticoSeralizer
from .historiamedicaSerializer import HistoriamedicaSerializers